# Generated by Django 5.1.2 on 2024-11-16 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('front-end', 'Front-End'), ('programacao', 'Programação'), ('generico', 'Assuntos gerais')], max_length=150, null=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='funcionalidades.certificado')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='funcionalidades.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.TextField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='funcionalidades.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('certificados', models.ManyToManyField(related_name='alunos', to='funcionalidades.certificado')),
                ('cursos', models.ManyToManyField(related_name='alunos', to='funcionalidades.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão')], max_length=10)),
                ('description', models.TextField(max_length=400)),
                ('date_alteration', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
