# Generated by Django 5.1.2 on 2024-11-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='certificados',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='funcionalidades.certificado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='funcionalidades.curso'),
        ),
    ]
